// frontend-angular/src/app/components/figura-list/figura-list.component.ts
// src/app/components/figura-list/figura-list.component.ts
// Componente para mostrar lista de figuras en una tabla.
// Este componente se suscribe al servicio para obtener datos y manejar creación, edición y eliminación.
import { Component, OnInit } from '@angular/core';
import { FiguraService, Figura } from '../../services/figura.service';

@Component({
  selector: 'app-figura-list',
  templateUrl: './figura-list.component.html',
  styleUrls: ['./figura-list.component.css']
})
export class FiguraListComponent implements OnInit {
  // Array que almacena las figuras obtenidas del backend
  figuras: Figura[] = [];

  // Bandera para mostrar/ocultar el formulario de creación/edición
  mostrarFormulario = false;

  // Objeto figura que se está editando (null si se está creando una nueva)
  figuraEdicion: Figura | null = null;

  // Variable para mostrar mensajes de carga
  cargando = false;

  // Variable para mostrar mensajes de error
  error: string | null = null;

  // Inyectamos el servicio de figuras en el constructor
  constructor(private figuraService: FiguraService) {}

  /**
   * ngOnInit()
   * Hook de Angular que se ejecuta al inicializar el componente.
   * Se usa para cargar las figuras del backend cuando se carga la página.
   */
  ngOnInit(): void {
    this.cargarFiguras();
  }

  /**
   * cargarFiguras()
   * Obtiene la lista de figuras del backend mediante el servicio.
   * 
   * Cómo funciona:
   * 1. Marca cargando = true para mostrar un spinner
   * 2. Llama al servicio figuraService.obtenerFiguras()
   * 3. Se suscribe a la respuesta (Observable)
   * 4. Guarda las figuras en this.figuras
   * 5. Limpia errores previos
   */
  cargarFiguras(): void {
    this.cargando = true;
    this.figuraService.obtenerFiguras().subscribe({
      next: (response) => {
        // response.data contiene el array de figuras del backend
        this.figuras = response.data || [];
        this.error = null;
        this.cargando = false;
      },
      error: (err) => {
        // Si hay error de conexión o en el backend
        this.error = 'Error al cargar las figuras. Verifica que el backend esté corriendo.';
        console.error('Error en cargarFiguras:', err);
        this.cargando = false;
      }
    });
  }

  /**
   * abrirFormulario()
   * Muestra el formulario para crear una nueva figura.
   * Reinicia figuraEdicion a null para indicar que es creación, no edición.
   */
  abrirFormulario(): void {
    this.mostrarFormulario = true;
    this.figuraEdicion = null;
  }

  /**
   * editarFigura()
   * Abre el formulario en modo edición con los datos de una figura existente.
   * 
   * @param figura - La figura a editar
   */
  editarFigura(figura: Figura): void {
    this.figuraEdicion = { ...figura }; // Copiar la figura para no modificar el original
    this.mostrarFormulario = true;
  }

  /**
   * guardarFigura()
   * Guarda una figura nueva o actualiza una existente, según si figuraEdicion tiene _id.
   * Se llama desde el componente hijo figura-form.
   * 
   * @param figura - La figura a guardar
   */
  guardarFigura(figura: Figura): void {
    if (figura._id) {
      // Es una edición: realizar PUT
      this.figuraService.actualizarFigura(figura._id, figura).subscribe({
        next: () => {
          this.cargarFiguras(); // Recargar la lista
          this.mostrarFormulario = false;
          alert('Figura actualizada exitosamente');
        },
        error: (err) => {
          alert('Error al actualizar la figura: ' + err.error.message);
        }
      });
    } else {
      // Es una creación: realizar POST
      this.figuraService.crearFigura(figura).subscribe({
        next: () => {
          this.cargarFiguras(); // Recargar la lista
          this.mostrarFormulario = false;
          alert('Figura creada exitosamente');
        },
        error: (err) => {
          alert('Error al crear la figura: ' + err.error.message);
        }
      });
    }
  }

  /**
   * eliminarFigura()
   * Elimina una figura después de confirmar con el usuario.
   * 
   * @param figura - La figura a eliminar
   */
  eliminarFigura(figura: Figura): void {
    if (figura._id && confirm('¿Estás seguro de que deseas eliminar esta figura?')) {
      this.figuraService.eliminarFigura(figura._id).subscribe({
        next: () => {
          this.cargarFiguras(); // Recargar la lista
          alert('Figura eliminada exitosamente');
        },
        error: (err) => {
          alert('Error al eliminar la figura: ' + err.error.message);
        }
      });
    }
  }

  /**
   * cerrarFormulario()
   * Oculta el formulario sin guardar cambios.
   */
  cerrarFormulario(): void {
    this.mostrarFormulario = false;
    this.figuraEdicion = null;
  }
}

<!-- src/app/components/figura-list/figura-list.component.html -->
<!-- Template para mostrar lista de figuras en una tabla Bootstrap con opciones CRUD -->

<div class="container mt-5">
  <!-- Encabezado y botón para crear nueva figura -->
  <div class="row mb-4">
    <div class="col-md-8">
      <h1>Colección de Figuras de Anime</h1>
    </div>
    <div class="col-md-4 text-end">
      <!-- Botón para abriri el formulario de creación -->
      <button 
        class="btn btn-primary"
        (click)="abrirFormulario()"
        [disabled]="mostrarFormulario">
        ➕ Nueva Figura
      </button>
    </div>
  </div>

  <!-- Mostrar mensaje de error si existe -->
  <div *ngIf="error" class="alert alert-danger alert-dismissible fade show" role="alert">
    {{ error }}
    <button type="button" class="btn-close" (click)="error = null"></button>
  </div>

  <!-- Mostrar spinner mientras se cargan las figuras -->
  <div *ngIf="cargando" class="text-center my-5">
    <div class="spinner-border" role="status">
      <span class="visually-hidden">Cargando...</span>
    </div>
  </div>

  <!-- Componente del formulario (se muestra solo si mostrarFormulario es true) -->
  <div *ngIf="mostrarFormulario" class="card mb-4 border-primary">
    <div class="card-header bg-primary text-white">
      {{ figuraEdicion ? 'Editar Figura' : 'Crear Nueva Figura' }}
    </div>
    <div class="card-body">
      <!-- El componente figura-form maneja el formulario -->
      <!-- Se pasa: figura actual (si es edición), evento al guardar, evento al cancelar -->
      <app-figura-form
        [figura]="figuraEdicion"
        (guardar)="guardarFigura($event)"
        (cancelar)="cerrarFormulario()">
      </app-figura-form>
    </div>
  </div>

  <!-- Tabla de figuras (solo se muestra si hay figuras y no se está cargando) -->
  <div *ngIf="!cargando && figuras.length > 0" class="table-responsive">
    <table class="table table-striped table-hover">
      <thead class="table-dark">
        <tr>
          <th>Nombre</th>
          <th>Anime</th>
          <th>Personaje</th>
          <th>Precio</th>
          <th>Stock</th>
          <th>Imagen</th>
          <th class="text-center">Acciones</th>
        </tr>
      </thead>
      <tbody>
        <!-- Recorrer array de figuras y mostrar una fila por cada una -->
        <tr *ngFor="let figura of figuras" [class.table-secondary]="mostrarFormulario">
          <!-- Nombre da la figura (enlace a la imagen si existe) -->
          <td>
            <strong>{{ figura.nombre }}</strong>
          </td>
          <!-- Anime -->
          <td>{{ figura.anime }}</td>
          <!-- Personaje (mostrar "-" si no hay) -->
          <td>{{ figura.personaje || '-' }}</td>
          <!-- Precio en formato moneda -->
          <td>{{ figura.precio ? ('$' + figura.precio) : '-' }}</td>
          <!-- Stock -->
          <td>
            <span class="badge" [class.bg-success]="figura.stock! > 0" [class.bg-danger]="figura.stock! === 0">
              {{ figura.stock || 0 }}
            </span>
          </td>
          <!-- Imagen: miniatura si existe, sino mensaje -->
          <td>
            <img 
              *ngIf="figura.imagen"
              [src]="figura.imagen"
              alt="{{ figura.nombre }}"
              class="img-thumbnail"
              style="width: 50px; height: 50px; object-fit: cover;">
            <span *ngIf="!figura.imagen" class="text-muted">-</span>
          </td>
          <!-- Botones para editar y eliminar -->
          <td class="text-center">
            <!-- Botón Editar: abre el formulario con los datos de la figura -->
            <button
              class="btn btn-sm btn-warning me-2"
              (click)="editarFigura(figura)"
              [disabled]="mostrarFormulario"
              title="Editar figura">
              ✏️ Editar
            </button>
            <!-- Botón Eliminar: solicita confirmación y elimina -->
            <button
              class="btn btn-sm btn-danger"
              (click)="eliminarFigura(figura)"
              [disabled]="mostrarFormulario"
              title="Eliminar figura">
              🗑️ Eliminar
            </button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <!-- Mensaje cuando no hay figuras -->
  <div *ngIf="!cargando && figuras.length === 0" class="alert alert-info">
    <strong>No hay figuras en la colección.</strong> ¡Crea una nueva haciendo clic en "Nueva Figura"!
  </div>
</div>

// frontend-react/src/components/FiguraList.jsx
// src/components/FiguraList.jsx
// Componente para listar todas las figuras de anime
// Obtiene datos del backend y permite crear, editar y eliminar figuras

import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { obtenerFiguras, eliminarFigura } from '../services/figuraService';
import './FiguraList.css';

export default function FiguraList() {
  // Estado para almacenar la lista de figuras obtenidas del backend
  const [figuras, setFiguras] = useState([]);
  
  // Estado para controlar si se están cargando datos
  const [cargando, setCargando] = useState(true);
  
  // Estado para mostrar mensajes de error
  const [error, setError] = useState(null);
  
  // Hook para navegar entre páginas
  const navigate = useNavigate();

  /**
   * useEffect - Hook que se ejecuta al montar el componente
   * Carga la lista de figuras del servidor backend
   */
  useEffect(() => {
    cargarFiguras();
  }, []);

  /**
   * cargarFiguras()
   * Función asincrónica que obtiene todas las figuras del backend
   * Maneja errores y actualiza el estado de carga
   */
  const cargarFiguras = async () => {
    try {
      setCargando(true);
      setError(null);
      const datos = await obtenerFiguras();
      setFiguras(datos);
    } catch (err) {
      // Si falla, muestra un mensaje de error útil
      setError('❌ No se pudo cargar las figuras. Verifica que el backend esté corriendo en puerto 5000');
      console.error('Error cargando figuras:', err);
    } finally {
      setCargando(false);
    }
  };

  /**
   * handleEliminar()
   * Solicita confirmación del usuario y elimina una figura
   * Luego recarga la lista de figuras
   * 
   * @param {string} id - ID de la figura a eliminar
   * @param {string} nombre - Nombre de la figura (para mostrar en confirmación)
   */
  const handleEliminar = async (id, nombre) => {
    // Mostrar confirmación antes de eliminar
    if (!window.confirm(`¿Estás seguro de que deseas eliminar "${nombre}"?`)) {
      return;
    }

    try {
      await eliminarFigura(id);
      alert('✅ Figura eliminada exitosamente');
      // Recargar la lista para reflejar cambios
      cargarFiguras();
    } catch (err) {
      alert('❌ Error al eliminar la figura: ' + err.message);
    }
  };

  return (
    <div className="list-container">
      <div className="container">
        
        {/* Encabezado con título y botón de crear */}
        <div className="list-header">
          <h1>📚 Colección de Figuras</h1>
          <button 
            className="btn-crear"
            onClick={() => navigate('/crear')}
            title="Crear nueva figura"
          >
            ➕ Nueva Figura
          </button>
        </div>

        {/* Mostrar alerta de error si existe */}
        {error && (
          <div className="alert alert-danger alert-dismissible fade show" role="alert">
            {error}
            <button 
              type="button" 
              className="btn-close" 
              onClick={() => setError(null)}
              aria-label="Close"
            ></button>
          </div>
        )}

        {/* Mostrar spinner (loading) mientras se cargan datos */}
        {cargando && (
          <div className="loading-spinner">
            <div className="spinner-border" role="status">
              <span className="visually-hidden">Cargando...</span>
            </div>
            <p>Cargando figuras...</p>
          </div>
        )}

        {/* Mostrar tabla de figuras si hay datos y no está cargando */}
        {!cargando && figuras.length > 0 && (
          <div className="table-responsive">
            <table className="table table-hover">
              <thead>
                <tr>
                  <th>Imagen</th>
                  <th>Nombre</th>
                  <th>Anime</th>
                  <th>Personaje</th>
                  <th>Precio</th>
                  <th>Stock</th>
                  <th>Acciones</th>
                </tr>
              </thead>
              <tbody>
                {/* Recorrer cada figura y mostrar una fila en la tabla */}
                {figuras.map((figura) => (
                  <tr key={figura._id}>
                    {/* Columna: Imagen */}
                    <td>
                      {figura?.imagen ? (
                        <img 
                          src={figura?.imagen} 
                          alt={figura.nombre}
                          className="tabla-imagen"
                          onError={(e) => e.target.style.display = 'none'}
                        />
                      ) : (
                        <div className="sin-imagen">🖼️</div>
                      )}
                    </td>

                    {/* Columna: Nombre */}
                    <td>
                      <strong>{figura.nombre}</strong>
                    </td>

                    {/* Columna: Anime */}
                    <td>{figura.anime || '-'}</td>

                    {/* Columna: Personaje */}
                    <td>{figura.personaje || '-'}</td>

                    {/* Columna: Precio */}
                    <td>
                      <span className="precio-fuerte">
                        ${(figura.precio || 0).toFixed(2)}
                      </span>
                    </td>

                    {/* Columna: Stock con badge */}
                    <td>
                      <span className={`badge-stock ${figura.stock > 0 ? 'badge-disponible' : 'badge-agotado'}`}>
                        {figura.stock || 0} {figura.stock === 1 ? 'unidad' : 'unidades'}
                      </span>
                    </td>

                    {/* Columna: Botones de acción (Editar, Eliminar) */}
                    <td>
                      <div className="celda-acciones">
                        {/* Botón Editar - navega a /editar/:id */}
                        <button
                          className="btn-tabla btn-editar"
                          onClick={() => navigate(`/editar/${figura._id}`, { state: { figura } })}
                          title={`Editar ${figura.nombre}`}
                        >
                          ✏️ Editar
                        </button>

                        {/* Botón Eliminar - solicita confirmación */}
                        <button
                          className="btn-tabla btn-eliminar"
                          onClick={() => handleEliminar(figura._id, figura.nombre)}
                          title={`Eliminar ${figura.nombre}`}
                        >
                          🗑️ Eliminar
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* Mostrar mensaje cuando no hay figuras */}
        {!cargando && figuras.length === 0 && !error && (
          <div className="empty-state">
            <h3>📭 La colección está vacía</h3>
            <p>No hay figuras registradas aún.</p>
            <button 
              className="btn-crear"
              onClick={() => navigate('/crear')}
            >
              ➕ Crear primera figura
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
