// frontend-angular/src/app/components/figura-form/figura-form.component.ts
// src/app/components/figura-form/figura-form.component.ts
// Componente formulario para crear o editar una figura.
// Recibe una figura como input y emite eventos de guardar o cancelar.
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Figura } from '../../services/figura.service';

@Component({
  selector: 'app-figura-form',
  templateUrl: './figura-form.component.html',
  styleUrls: ['./figura-form.component.css']
})
export class FiguraFormComponent implements OnInit {
  // Input: figura a editar (null si es creación nueva)
  @Input() figura: Figura | null = null;

  // Output: evento que emite cuando se guarda la figura
  @Output() guardar = new EventEmitter<Figura>();

  // Output: evento que emite cuando se cancela la edición
  @Output() cancelar = new EventEmitter<void>();

  // Grupo de control del formulario (FormGroup)
  // Maneja la validación y el estado de todos los campos
  formulario!: FormGroup;

  // Constructor: inyectamos FormBuilder para crear el formulario reactivo
  constructor(private fb: FormBuilder) {}

  /**
   * ngOnInit()
   * Hook de Angular que se ejecuta al inicializar el componente.
   * Crea el formulario y lo llena con datos si es edición.
   */
  ngOnInit(): void {
    this.crearFormulario();
    this.llenarFormulario();
  }

  /**
   * crearFormulario()
   * Crea un FormGroup reactivo con validaciones.
   * 
   * FormControl(valor, validadores):
   * - Validators.required: el campo es obligatorio
   * - Validators.minLength(n): mínimo n caracteres
   * - Validators.min(n): valor mínimo n
   */
  crearFormulario(): void {
    this.formulario = this.fb.group({
      // Campo nombre: obligatorio, entre 3 y 100 caracteres
      nombre: ['', [Validators.required, Validators.minLength(3), Validators.maxLength(100)]],

      // Campo anime: obligatorio, entre 3 y 100 caracteres
      anime: ['', [Validators.required, Validators.minLength(3), Validators.maxLength(100)]],

      // Campo personaje: opcional
      personaje: [''],

      // Campo precio: opcional, mínimo 0
      precio: [0, [Validators.min(0)]],

      // Campo stock: opcional, mínimo 0 (debe ser un número entero)
      stock: [0, [Validators.min(0)]],

      // Campo imagen: opcional (URL)
      imagen: ['']
    });
  }

  /**
   * llenarFormulario()
   * Si se está editando una figura, rellena el formulario con sus datos.
   */
  llenarFormulario(): void {
    if (this.figura && this.figura._id) {
      // Si figura tiene _id, es edición
      this.formulario.patchValue({
        nombre: this.figura.nombre,
        anime: this.figura.anime,
        personaje: this.figura.personaje || '',
        precio: this.figura.precio || 0,
        stock: this.figura.stock || 0,
        imagen: this.figura.imagen || ''
      });
    }
  }

  /**
   * onSubmit()
   * Se ejecuta cuando se envía el formulario (clic en Guardar).
   * 
   * Cómo funciona:
   * 1. Valida que todos los campos requeridos estén completos
   * 2. Si es válido, crea un objeto Figura con los datos del formulario
   * 3. Si es edición, incluye el _id original
   * 4. Emite el evento 'guardar' al componente padre (figura-list)
   * 5. El componente padre llama a figuraService.crearFigura() o .actualizarFigura()
   */
  onSubmit(): void {
    // Verificar que el formulario sea válido
    if (this.formulario.invalid) {
      alert('Por favor completa todos los campos requeridos correctamente.');
      return;
    }

    // Obtener los valores del formulario
    const formValues = this.formulario.value;

    // Crear un objeto Figura con los datos
    const novaFigura: Figura = {
      nombre: formValues.nombre,
      anime: formValues.anime,
      personaje: formValues.personaje || undefined,
      precio: formValues.precio || 0,
      stock: formValues.stock || 0,
      imagen: formValues.imagen || undefined
    };

    // Si es edición, incluir el _id original
    if (this.figura && this.figura._id) {
      novaFigura._id = this.figura._id;
    }

    // Emitir evento al componente padre con la figura a guardar
    this.guardar.emit(novaFigura);
  }

  /**
   * onCancelar()
   * Se ejecuta cuando se hace clic en el botón "Cancelar".
   * Emite el evento 'cancelar' al componente padre.
   */
  onCancelar(): void {
    this.cancelar.emit();
  }
}

<!-- src/app/components/figura-form/figura-form.component.html -->
<!-- Formulario reactivo para crear/editar figuras usando Bootstrap 5 -->

<form [formGroup]="formulario" (ngSubmit)="onSubmit()">
  <!-- Fila 1: Nombre y Anime (campos requeridos) -->
  <div class="row mb-3">
    <!-- Campo Nombre -->
    <div class="col-md-6">
      <label for="nombre" class="form-label">
        Nombre <span class="text-danger">*</span>
      </label>
      <input
        type="text"
        class="form-control"
        id="nombre"
        formControlName="nombre"
        placeholder="Ej: Saitama Statue"
        [class.is-invalid]="formulario.get('nombre')?.invalid && formulario.get('nombre')?.touched">
      <!-- Mostrar mensajes de error -->
      <div class="invalid-feedback d-block" *ngIf="formulario.get('nombre')?.hasError('required')">
        El nombre es requerido.
      </div>
      <div class="invalid-feedback d-block" *ngIf="formulario.get('nombre')?.hasError('minlength')">
        El nombre debe tener al menos 3 caracteres.
      </div>
    </div>

    <!-- Campo Anime -->
    <div class="col-md-6">
      <label for="anime" class="form-label">
        Anime <span class="text-danger">*</span>
      </label>
      <input
        type="text"
        class="form-control"
        id="anime"
        formControlName="anime"
        placeholder="Ej: One Punch Man"
        [class.is-invalid]="formulario.get('anime')?.invalid && formulario.get('anime')?.touched">
      <!-- Mostrar mensajes de error -->
      <div class="invalid-feedback d-block" *ngIf="formulario.get('anime')?.hasError('required')">
        El anime es requerido.
      </div>
      <div class="invalid-feedback d-block" *ngIf="formulario.get('anime')?.hasError('minlength')">
        El anime debe tener al menos 3 caracteres.
      </div>
    </div>
  </div>

  <!-- Fila 2: Personaje y Precio -->
  <div class="row mb-3">
    <!-- Campo Personaje -->
    <div class="col-md-6">
      <label for="personaje" class="form-label">Personaje</label>
      <input
        type="text"
        class="form-control"
        id="personaje"
        formControlName="personaje"
        placeholder="Ej: Saitama">
    </div>

    <!-- Campo Precio -->
    <div class="col-md-6">
      <label for="precio" class="form-label">Precio ($)</label>
      <input
        type="number"
        class="form-control"
        id="precio"
        formControlName="precio"
        placeholder="0.00"
        step="0.01"
        min="0"
        [class.is-invalid]="formulario.get('precio')?.invalid && formulario.get('precio')?.touched">
      <div class="invalid-feedback d-block" *ngIf="formulario.get('precio')?.hasError('min')">
        El precio no puede ser negativo.
      </div>
    </div>
  </div>

  <!-- Fila 3: Stock e Imagen -->
  <div class="row mb-3">
    <!-- Campo Stock -->
    <div class="col-md-6">
      <label for="stock" class="form-label">Stock (Cantidad)</label>
      <input
        type="number"
        class="form-control"
        id="stock"
        formControlName="stock"
        placeholder="0"
        min="0"
        [class.is-invalid]="formulario.get('stock')?.invalid && formulario.get('stock')?.touched">
      <div class="invalid-feedback d-block" *ngIf="formulario.get('stock')?.hasError('min')">
        El stock no puede ser negativo.
      </div>
    </div>

    <!-- Campo Imagen (URL) -->
    <div class="col-md-6">
      <label for="imagen" class="form-label">URL de Imagen</label>
      <input
        type="url"
        class="form-control"
        id="imagen"
        formControlName="imagen"
        placeholder="https://ejemplo.com/imagen.jpg">
    </div>
  </div>

  <!-- Botones de acción: Guardar y Cancelar -->
  <div class="d-flex gap-2">
    <!-- Botón Guardar: enviará el formulario si es válido -->
    <button
      type="submit"
      class="btn btn-success"
      [disabled]="formulario.invalid">
      💾 Guardar
    </button>

    <!-- Botón Cancelar: emite evento de cancelación sin guardar -->
    <button
      type="button"
      class="btn btn-secondary"
      (click)="onCancelar()">
      ❌ Cancelar
    </button>
  </div>

  <!-- Nota sobre campos requeridos -->
  <small class="d-block mt-3 text-muted">
    <span class="text-danger">*</span> Campo requerido
  </small>
</form>

// frontend-react/src/components/FiguraForm.jsx
// src/components/FiguraForm.jsx
// Componente formulario para crear o editar figuras de anime
// Puede funcionar en modo creación (sin figura) o edición (con figura existente)

import React, { useState, useEffect } from 'react';
import { useNavigate, useParams, useLocation } from 'react-router-dom';
import { crearFigura, actualizarFigura } from '../services/figuraService';
import './FiguraForm.css';

export default function FiguraForm() {
  // Hook para obtener el ID de la URL (usado solo en edición)
  const { id } = useParams();
  
  // Hook para navegar entre páginas
  const navigate = useNavigate();
  
  // Hook para obtener datos pasados en navegación (figura editada)
  const location = useLocation();
  const figuraEditada = location.state?.figura;

  // Estado del formulario - almacena los valores de cada input
  const [formData, setFormData] = useState({
    nombre: '',
    anime: '',
    personaje: '',
    precio: 0,
    stock: 0,
    imagen: ''
  });

  // Estado para mostrar loading mientras se guarda
  const [guardando, setGuardando] = useState(false);

  // Estado para mostrar errores
  const [errores, setErrores] = useState({});

  /**
   * useEffect - Se ejecuta al montar el componente
   * Si viene en modo edición, carga los datos de la figura
   */
  useEffect(() => {
    if (figuraEditada && id) {
      // Modo edición: llenar el formulario con datos existentes
      setFormData({
        nombre: figuraEditada.nombre || '',
        anime: figuraEditada.anime || '',
        personaje: figuraEditada.personaje || '',
        precio: figuraEditada.precio || 0,
        stock: figuraEditada.stock || 0,
        imagen: figuraEditada.imagen || ''
      });
    }
  }, [id, figuraEditada]);

  /**
   * handleChange()
   * Se ejecuta cuando cambia el valor de un input
   * Actualiza el estado formData
   * 
   * @param {event} e - Evento del input
   */
  const handleChange = (e) => {
    const { name, value } = e.target;
    
    // Convertir a número si el campo es precio o stock
    let finalValue = value;
    if (name === 'precio' || name === 'stock') {
      finalValue = parseFloat(value) || 0;
    }

    setFormData(prev => ({
      ...prev,
      [name]: finalValue
    }));

    // Limpiar error de este campo cuando el usuario empieza a escribir
    if (errores[name]) {
      setErrores(prev => ({
        ...prev,
        [name]: ''
      }));
    }
  };

  /**
   * validarFormulario()
   * Valida que los campos requeridos estén completos
   * 
   * @returns {boolean} true si el formulario es válido
   */
  const validarFormulario = () => {
    const nuevosErrores = {};

    if (!formData.nombre.trim()) {
      nuevosErrores.nombre = 'El nombre es requerido';
    } else if (formData.nombre.trim().length < 3) {
      nuevosErrores.nombre = 'El nombre debe tener al menos 3 caracteres';
    }

    if (!formData.anime.trim()) {
      nuevosErrores.anime = 'El anime es requerido';
    } else if (formData.anime.trim().length < 3) {
      nuevosErrores.anime = 'El anime debe tener al menos 3 caracteres';
    }

    if (formData.precio < 0) {
      nuevosErrores.precio = 'El precio no puede ser negativo';
    }

    if (formData.stock < 0) {
      nuevosErrores.stock = 'El stock no puede ser negativo';
    }

    setErrores(nuevosErrores);
    return Object.keys(nuevosErrores).length === 0;
  };

  /**
   * handleSubmit()
   * Se ejecuta al enviar el formulario
   * Valida, guarda en el backend y navega al listado
   * 
   * @param {event} e - Evento del formulario
   */
  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!validarFormulario()) {
      alert('Por favor completa todos los campos requeridos correctamente');
      return;
    }

    setGuardando(true);

    try {
      if (id) {
        // Modo edición: usar PUT
        await actualizarFigura(id, formData);
        alert('Figura actualizada exitosamente');
      } else {
        // Modo creación: usar POST
        await crearFigura(formData);
        alert('Figura creada exitosamente');
      }

      // Navegar al listado
      navigate('/');
    } catch (err) {
      alert('Error al guardar la figura: ' + err.message);
    } finally {
      setGuardando(false);
    }
  };

  return (
    <div className="container form-container">
      <div className="form-header">
        <h1>{id ? '✏️ Editar Figura' : '➕ Nueva Figura'}</h1>
      </div>

      <form onSubmit={handleSubmit} className="figura-form">
        
        {/* Fila 1: Nombre y Anime */}
        <div className="form-row">
          <div className="form-group">
            <label htmlFor="nombre">Nombre *</label>
            <input
              type="text"
              id="nombre"
              name="nombre"
              value={formData.nombre}
              onChange={handleChange}
              placeholder="Ej: Saitama Statue"
              className={errores.nombre ? 'input-error' : ''}
            />
            {errores.nombre && <span className="error-message">{errores.nombre}</span>}
          </div>

          <div className="form-group">
            <label htmlFor="anime">Anime *</label>
            <input
              type="text"
              id="anime"
              name="anime"
              value={formData.anime}
              onChange={handleChange}
              placeholder="Ej: One Punch Man"
              className={errores.anime ? 'input-error' : ''}
            />
            {errores.anime && <span className="error-message">{errores.anime}</span>}
          </div>
        </div>

        {/* Fila 2: Personaje */}
        <div className="form-row">
          <div className="form-group full-width">
            <label htmlFor="personaje">Personaje</label>
            <input
              type="text"
              id="personaje"
              name="personaje"
              value={formData.personaje}
              onChange={handleChange}
              placeholder="Ej: Saitama (opcional)"
            />
          </div>
        </div>

        {/* Fila 3: Precio y Stock */}
        <div className="form-row">
          <div className="form-group">
            <label htmlFor="precio">Precio ($)</label>
            <input
              type="number"
              id="precio"
              name="precio"
              value={formData.precio}
              onChange={handleChange}
              placeholder="0.00"
              step="0.01"
              min="0"
              className={errores.precio ? 'input-error' : ''}
            />
            {errores.precio && <span className="error-message">{errores.precio}</span>}
          </div>

          <div className="form-group">
            <label htmlFor="stock">Stock (Cantidad)</label>
            <input
              type="number"
              id="stock"
              name="stock"
              value={formData.stock}
              onChange={handleChange}
              placeholder="0"
              min="0"
              className={errores.stock ? 'input-error' : ''}
            />
            {errores.stock && <span className="error-message">{errores.stock}</span>}
          </div>
        </div>

        {/* Fila 4: Imagen */}
        <div className="form-row">
          <div className="form-group full-width">
            <label htmlFor="imagen">URL de Imagen</label>
            <input
              type="url"
              id="imagen"
              name="imagen"
              value={formData.imagen}
              onChange={handleChange}
              placeholder="https://ejemplo.com/imagen.jpg (opcional)"
            />
          </div>
        </div>

        {/* Vista previa de imagen si existe */}
        {formData.imagen && (
          <div className="form-row">
            <div className="imagen-preview">
              <p>Vista previa:</p>
              <img src={formData.imagen} alt="Vista previa" onError={(e) => e.target.style.display = 'none'} />
            </div>
          </div>
        )}

        {/* Botones de acción */}
        <div className="form-actions">
          <button
            type="submit"
            className="btn btn-primary btn-lg"
            disabled={guardando}
          >
            {guardando ? 'Guardando...' : (id ? '💾 Actualizar' : '💾 Crear')}
          </button>
          <button
            type="button"
            className="btn btn-secondary btn-lg"
            onClick={() => navigate('/')}
            disabled={guardando}
          >
            ❌ Cancelar
          </button>
        </div>

        {/* Nota sobre campos requeridos */}
        <small className="required-note">* Campo requerido</small>
      </form>
    </div>
  );
}
