// frontend-angular/src/app/components/figura-form/figura-form.component.ts
// src/app/components/figura-form/figura-form.component.ts
// Componente formulario para crear o editar una figura.
// Recibe una figura como input y emite eventos de guardar o cancelar.
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { FiguraService, Figura } from '../../services/figura.service';

@Component({
  selector: 'app-figura-form',
  templateUrl: './figura-form.component.html',
  styleUrls: ['./figura-form.component.css']
})
export class FiguraFormComponent implements OnInit {

  id: string | null = null;
  loading = false;
  error: string | null = null;
  success = false;

  // Grupo de control del formulario (FormGroup)
  // Maneja la validación y el estado de todos los campos
  formulario!: FormGroup;
  figura: Figura | null = null;

  // Constructor: inyectamos FormBuilder para crear el formulario reactivo
  constructor(
    private fb: FormBuilder,
    private figuraService: FiguraService,
    private route: ActivatedRoute,
    private router: Router
  ) {}

  /**
   * ngOnInit()
   * Hook de Angular que se ejecuta al inicializar el componente.
   * Crea el formulario y lo llena con datos si es edición.
   */
  ngOnInit(): void {
    this.crearFormulario();
    this.id = this.route.snapshot.paramMap.get('id');
    if (this.id) {
      this.loading = true;
      this.figuraService.getById(this.id).subscribe({
        next: (figura) => {
          this.figura = figura;
          this.llenarFormulario();
          this.loading = false;
        },
        error: (err) => {
          this.error = 'No se pudo cargar la figura.';
          this.loading = false;
        }
      });
    }
  }

  /**
   * crearFormulario()
   * Crea un FormGroup reactivo con validaciones.
   * 
   * FormControl(valor, validadores):
   * - Validators.required: el campo es obligatorio
   * - Validators.minLength(n): mínimo n caracteres
   * - Validators.min(n): valor mínimo n
   */
  crearFormulario(): void {
    this.formulario = this.fb.group({
      // Campo nombre: obligatorio, entre 3 y 100 caracteres
      nombre: ['', [Validators.required, Validators.minLength(3), Validators.maxLength(100)]],

      // Campo anime: obligatorio, entre 3 y 100 caracteres
      anime: ['', [Validators.required, Validators.minLength(3), Validators.maxLength(100)]],

      // Campo personaje: opcional
      personaje: [''],

      // Campo precio: opcional, mínimo 0
      precio: [0, [Validators.min(0)]],

      // Campo stock: opcional, mínimo 0 (debe ser un número entero)
      stock: [0, [Validators.min(0)]],

      // Campo imagen: opcional (URL)
      imagen: [''],
      malId: ['']
    });
  }

  /**
   * llenarFormulario()
   * Si se está editando una figura, rellena el formulario con sus datos.
   */
  llenarFormulario(): void {
    if (this.figura) {
      this.formulario.patchValue({
        nombre: this.figura.nombre,
        anime: this.figura.anime,
        personaje: this.figura.personaje || '',
        precio: this.figura.precio || 0,
        stock: this.figura.stock || 0,
        imagen: this.figura?.imagen || '',
        malId: this.figura.malId || ''
      });
    }
  }

  /**
   * onSubmit()
   * Se ejecuta cuando se envía el formulario (clic en Guardar).
   * 
   * Cómo funciona:
   * 1. Valida que todos los campos requeridos estén completos
   * 2. Si es válido, crea un objeto Figura con los datos del formulario
   * 3. Si es edición, incluye el _id original
   * 4. Emite el evento 'guardar' al componente padre (figura-list)
   * 5. El componente padre llama a figuraService.crearFigura() o .actualizarFigura()
   */
  onSubmit(): void {
    if (this.formulario.invalid) {
      this.error = 'Por favor completa todos los campos requeridos correctamente.';
      return;
    }
    this.loading = true;
    this.error = null;
    this.success = false;
    const payload: Figura = this.formulario.value;
    if (this.id) {
      // Editar
      this.figuraService.update(this.id, payload).subscribe({
        next: () => {
          this.success = true;
          this.loading = false;
          this.router.navigate(['/figuras'], { queryParams: { msg: 'Figura actualizada correctamente.' } });
        },
        error: (err) => {
          this.error = 'Error al actualizar la figura.';
          this.loading = false;
        }
      });
    } else {
      // Crear
      this.figuraService.create(payload).subscribe({
        next: () => {
          this.success = true;
          this.loading = false;
          this.router.navigate(['/figuras'], { queryParams: { msg: 'Figura creada correctamente.' } });
        },
        error: (err) => {
          this.error = 'Error al crear la figura.';
          this.loading = false;
        }
      });
    }
  }

  /**
   * onCancelar()
   * Se ejecuta cuando se hace clic en el botón "Cancelar".
   * Emite el evento 'cancelar' al componente padre.
   */
  onCancelar(): void {
    this.router.navigate(['/figuras']);
  }

  get titulo(): string {
    return this.id ? 'Editar figura' : 'Nueva figura';
  }
}

<form [formGroup]="formulario" (ngSubmit)="onSubmit()" class="p-3 border rounded bg-light">
  <h3 class="mb-4">{{ titulo }}</h3>
  <div class="mb-3">
    <label for="nombre" class="form-label">Nombre *</label>
    <input id="nombre" type="text" class="form-control" formControlName="nombre" required
      [ngClass]="{'is-invalid': formulario.get('nombre')?.touched && formulario.get('nombre')?.invalid}">
    <div *ngIf="formulario.get('nombre')?.touched && formulario.get('nombre')?.invalid" class="invalid-feedback">
      <div *ngIf="formulario.get('nombre')?.errors?.['required']">El nombre es obligatorio.</div>
      <div *ngIf="formulario.get('nombre')?.errors?.['minlength']">Mínimo 3 caracteres.</div>
    </div>
  </div>
  <div class="mb-3">
    <label for="anime" class="form-label">Anime *</label>
    <input id="anime" type="text" class="form-control" formControlName="anime" required
      [ngClass]="{'is-invalid': formulario.get('anime')?.touched && formulario.get('anime')?.invalid}">
    <div *ngIf="formulario.get('anime')?.touched && formulario.get('anime')?.invalid" class="invalid-feedback">
      <div *ngIf="formulario.get('anime')?.errors?.['required']">El anime es obligatorio.</div>
      <div *ngIf="formulario.get('anime')?.errors?.['minlength']">Mínimo 3 caracteres.</div>
    </div>
  </div>
  <div class="mb-3">
    <label for="personaje" class="form-label">Personaje</label>
    <input id="personaje" type="text" class="form-control" formControlName="personaje">
  </div>
  <div class="mb-3">
    <label for="precio" class="form-label">Precio</label>
    <input id="precio" type="number" class="form-control" formControlName="precio" min="0"
      [ngClass]="{'is-invalid': formulario.get('precio')?.touched && formulario.get('precio')?.invalid}">
    <div *ngIf="formulario.get('precio')?.touched && formulario.get('precio')?.invalid" class="invalid-feedback">
      <div *ngIf="formulario.get('precio')?.errors?.['min']">El precio debe ser mayor o igual a 0.</div>
    </div>
  </div>
  <div class="mb-3">
    <label for="stock" class="form-label">Stock</label>
    <input id="stock" type="number" class="form-control" formControlName="stock" min="0"
      [ngClass]="{'is-invalid': formulario.get('stock')?.touched && formulario.get('stock')?.invalid}">
    <div *ngIf="formulario.get('stock')?.touched && formulario.get('stock')?.invalid" class="invalid-feedback">
      <div *ngIf="formulario.get('stock')?.errors?.['min']">El stock debe ser mayor o igual a 0.</div>
    </div>
  </div>
  <div class="mb-3">
    <label for="imagen" class="form-label">Imagen (URL)</label>
    <input id="imagen" type="text" class="form-control" formControlName="imagen">
  </div>
  <div class="mb-3">
    <label for="malId" class="form-label">malId (opcional)</label>
    <input id="malId" type="number" class="form-control" formControlName="malId">
  </div>
  <div class="d-flex gap-2">
    <button type="submit" class="btn btn-primary" [disabled]="formulario.invalid || loading">
      <span *ngIf="loading" class="spinner-border spinner-border-sm me-2"></span>
      Guardar
    </button>
    <button type="button" class="btn btn-secondary" (click)="onCancelar()" [disabled]="loading">Cancelar</button>
  </div>
  <div *ngIf="error" class="alert alert-danger mt-2">{{ error }}</div>
</form>

// frontend-react/src/pages/FiguraForm.jsx
// Formulario para crear o editar una figura
// Incluye validaciones, feedback visual y diseño profesional con Bootstrap

import React, { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { create, update, getById } from "../services/figurasApi";

const initialForm = {
  nombre: "",
  anime: "",
  personaje: "",
  precio: "",
  stock: "",
  imagen: "",
  malId: "",
};

function FiguraForm() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [form, setForm] = useState(initialForm);
  const [loading, setLoading] = useState(!!id);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [successMsg, setSuccessMsg] = useState("");
  const [fieldErrors, setFieldErrors] = useState({});

  // Si hay id, carga los datos para edición
  useEffect(() => {
    if (id) {
      setLoading(true);
      getById(id)
        .then((data) => {
          setForm({
            nombre: data.nombre || "",
            anime: data.anime || "",
            personaje: data.personaje || "",
            precio: data.precio != null ? String(data.precio) : "",
            stock: data.stock != null ? String(data.stock) : "",
            imagen: data.imagen || "",
            malId: data.malId != null ? String(data.malId) : "",
          });
          setLoading(false);
        })
        .catch(() => {
          setError("No se pudo cargar la figura.");
          setLoading(false);
        });
    }
  }, [id]);

  // Validaciones de campos antes de enviar
  const validate = () => {
    const errors = {};
    if (!form.nombre.trim()) errors.nombre = "El nombre es requerido.";
    if (!form.anime.trim()) errors.anime = "El anime es requerido.";
    if (form.precio === "" || isNaN(form.precio) || Number(form.precio) < 0)
      errors.precio = "El precio debe ser un número mayor o igual a 0.";
    if (form.stock === "" || isNaN(form.stock) || Number(form.stock) < 0)
      errors.stock = "El stock debe ser un número mayor o igual a 0.";
    if (form.malId && (isNaN(form.malId) || !Number.isInteger(Number(form.malId))))
      errors.malId = "malId debe ser un número entero.";
    return errors;
  };

  // Manejo de cambios en los inputs
  const handleChange = (e) => {
    const { name, value } = e.target;
    setForm((prev) => ({
      ...prev,
      [name]: value,
    }));
    setFieldErrors((prev) => ({
      ...prev,
      [name]: undefined,
    }));
  };

  // Envío del formulario (crear o actualizar)
  const handleSubmit = async (e) => {
    e.preventDefault();
    setError("");
    setSuccessMsg("");
    const errors = validate();
    setFieldErrors(errors);
    if (Object.keys(errors).length > 0) return;

    setSaving(true);
    try {
      const payload = {
        ...form,
        precio: Number(form.precio),
        stock: Number(form.stock),
      };
      if (!payload.malId) {
        delete payload.malId;
      } else {
        payload.malId = Number(payload.malId);
      }
      if (id) {
        await update(id, payload);
        setSuccessMsg("Figura actualizada correctamente.");
      } else {
        await create(payload);
        setSuccessMsg("Figura creada correctamente.");
      }
      setTimeout(() => navigate("/figuras"), 1200);
    } catch (err) {
      setError("Ocurrió un error al guardar la figura.");
    } finally {
      setSaving(false);
    }
  };

  // Feedback de carga
  if (loading) {
    return (
      <div className="d-flex justify-content-center mt-5">
        <div className="spinner-border" role="status" aria-label="Cargando"></div>
      </div>
    );
  }

  return (
    <div className="row justify-content-center mt-4">
      <div className="col-md-8">
        {/* Card principal del formulario */}
        <div className="card bg-secondary text-light shadow">
          {/* Header dinámico según modo (crear/editar) */}
          <div className="card-header text-center">
            <h3 className="mb-0">
              <i className={`bi ${id ? "bi-pencil-square" : "bi-plus-circle"} me-2`}></i>
              {id ? "Editar Figura" : "Nueva Figura"}
            </h3>
          </div>
          <div className="card-body">
            {/* Mensajes de error y éxito */}
            {error && (
              <div className="alert alert-danger" role="alert">
                {error}
              </div>
            )}
            {successMsg && (
              <div className="alert alert-success" role="alert">
                {successMsg}
              </div>
            )}
            {/* Formulario controlado con validaciones visuales */}
            <form onSubmit={handleSubmit} noValidate>
              <div className="mb-3">
                <label className="form-label">Nombre *</label>
                <input
                  type="text"
                  className={`form-control${fieldErrors.nombre ? " is-invalid" : ""}`}
                  name="nombre"
                  value={form.nombre}
                  onChange={handleChange}
                  disabled={saving}
                />
                {fieldErrors.nombre && (
                  <div className="invalid-feedback">{fieldErrors.nombre}</div>
                )}
              </div>
              <div className="mb-3">
                <label className="form-label">Anime *</label>
                <input
                  type="text"
                  className={`form-control${fieldErrors.anime ? " is-invalid" : ""}`}
                  name="anime"
                  value={form.anime}
                  onChange={handleChange}
                  disabled={saving}
                />
                {fieldErrors.anime && (
                  <div className="invalid-feedback">{fieldErrors.anime}</div>
                )}
              </div>
              <div className="mb-3">
                <label className="form-label">Personaje</label>
                <input
                  type="text"
                  className="form-control"
                  name="personaje"
                  value={form.personaje}
                  onChange={handleChange}
                  disabled={saving}
                />
              </div>
              <div className="mb-3">
                <label className="form-label">Precio *</label>
                <input
                  type="number"
                  className={`form-control${fieldErrors.precio ? " is-invalid" : ""}`}
                  name="precio"
                  value={form.precio}
                  onChange={handleChange}
                  min="0"
                  disabled={saving}
                />
                {fieldErrors.precio && (
                  <div className="invalid-feedback">{fieldErrors.precio}</div>
                )}
              </div>
              <div className="mb-3">
                <label className="form-label">Stock *</label>
                <input
                  type="number"
                  className={`form-control${fieldErrors.stock ? " is-invalid" : ""}`}
                  name="stock"
                  value={form.stock}
                  onChange={handleChange}
                  min="0"
                  disabled={saving}
                />
                {fieldErrors.stock && (
                  <div className="invalid-feedback">{fieldErrors.stock}</div>
                )}
              </div>
              <div className="mb-3">
                <label className="form-label">Imagen (URL)</label>
                <input
                  type="text"
                  className="form-control"
                  name="imagen"
                  value={form.imagen}
                  onChange={handleChange}
                  disabled={saving}
                />
              </div>
              <div className="mb-3">
                <label className="form-label">malId</label>
                <input
                  type="text"
                  className={`form-control${fieldErrors.malId ? " is-invalid" : ""}`}
                  name="malId"
                  value={form.malId}
                  onChange={handleChange}
                  disabled={saving}
                />
                {fieldErrors.malId && (
                  <div className="invalid-feedback">{fieldErrors.malId}</div>
                )}
              </div>
              {/* Botones alineados a la derecha con iconos */}
              <div className="d-flex justify-content-end gap-2 mt-4">
                <button type="submit" className="btn btn-primary" disabled={saving}>
                  <i className="bi bi-save me-1"></i>
                  {saving ? "Guardando..." : "Guardar"}
                </button>
                <button
                  type="button"
                  className="btn btn-secondary"
                  onClick={() => navigate("/figuras")}
                  disabled={saving}
                >
                  <i className="bi bi-arrow-left me-1"></i>
                  Cancelar
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}

export default FiguraForm;
