// frontend-angular/src/app/components/figura-detail/figura-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FiguraService, Figura } from '../../services/figura.service';

@Component({
  selector: 'app-figura-detail',
  templateUrl: './figura-detail.component.html',
  styleUrls: ['./figura-detail.component.css']
})
export class FiguraDetailComponent implements OnInit {
  figura: Figura | null = null;
  loading = false;
  error: string | null = null;
  showModal = false;
  loadingDelete = false;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private figuraService: FiguraService
  ) {}

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.loading = true;
      this.figuraService.getById(id).subscribe({
        next: (fig) => {
          this.figura = fig;
          this.loading = false;
        },
        error: () => {
          this.error = 'No se pudo cargar la figura.';
          this.loading = false;
        }
      });
    } else {
      this.error = 'ID no válido.';
    }
  }

  volver(): void {
    this.router.navigate(['/figuras']);
  }

  editar(): void {
    if (this.figura && this.figura._id) {
      this.router.navigate(['/figuras/editar', this.figura._id]);
    }
  }

  confirmarEliminar() {
    if (!this.figura || !this.figura._id) return;
    if (!confirm(`¿Eliminar "${this.figura.nombre}"?`)) return;
    this.loadingDelete = true;
    this.figuraService.delete(this.figura._id).subscribe({
      next: () => {
        this.loadingDelete = false;
        this.router.navigate(['/figuras'], { queryParams: { msg: 'Figura eliminada correctamente.' } });
      },
      error: () => {
        this.error = 'Error al eliminar la figura.';
        this.loadingDelete = false;
      }
    });
  }
}

<div class="container mt-4">
  <div *ngIf="loading" class="alert alert-info d-flex align-items-center gap-2">
    <div class="spinner-border spinner-border-sm" role="status"></div>
    <span>Cargando...</span>
  </div>
  <div *ngIf="error" class="alert alert-danger">{{ error }}</div>

  <ng-container *ngIf="figura as f">
    <div class="card shadow">
      <div class="card-header d-flex justify-content-between align-items-center">
        <h4 class="mb-0">Detalle de Figura</h4>
        <span class="badge bg-secondary">ID: {{ f._id }}</span>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-md-8">
            <table class="table table-borderless mb-0">
              <tbody>
                <tr><th>Nombre</th><td>{{ f.nombre }}</td></tr>
                <tr><th>Anime</th><td>{{ f.anime }}</td></tr>
                <tr><th>Personaje</th><td>{{ f.personaje || '-' }}</td></tr>
                <tr><th>Precio</th><td>{{ f.precio | currency:'EUR':'symbol':'1.0-2' }}</td></tr>
                <tr><th>Stock</th><td>{{ f.stock }}</td></tr>
                <tr><th>malId</th><td>{{ f.malId || '-' }}</td></tr>
                <tr *ngIf="f.imagen">
                  <th>Imagen</th>
                  <td>
                    <ng-container *ngIf="f.imagen.startsWith('http'); else textoImagen">
                      <img [src]="f.imagen" [alt]="f.nombre" class="img-fluid rounded" style="max-height: 200px; object-fit: cover;">
                    </ng-container>
                    <ng-template #textoImagen>{{ f.imagen }}</ng-template>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="card-footer d-flex gap-2 justify-content-end">
        <button class="btn btn-secondary" (click)="volver()">
          <i class="bi bi-arrow-left"></i> Volver
        </button>
        <button class="btn btn-primary" (click)="editar()">
          <i class="bi bi-pencil"></i> Editar
        </button>
        <button class="btn btn-danger" (click)="confirmarEliminar()" [disabled]="loadingDelete">
          <span *ngIf="loadingDelete" class="spinner-border spinner-border-sm me-1"></span>
          <i class="bi bi-trash"></i> Eliminar
        </button>
      </div>
    </div>
  </ng-container>
<ng-template #textoImagen>{{ figura?.imagen }}</ng-template>
</div>

// frontend-react/src/pages/FiguraDetail.jsx
import React, { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { getById, remove } from "../services/figurasApi";

function FiguraDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [figura, setFigura] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [successMsg, setSuccessMsg] = useState("");

  useEffect(() => {
    setLoading(true);
    setError("");
    getById(id)
      .then((data) => {
        setFigura(data);
        setLoading(false);
      })
      .catch(() => {
        setError("No se pudo cargar la figura.");
        setLoading(false);
      });
  }, [id]);

  const handleDelete = async () => {
    if (!window.confirm("¿Seguro que deseas eliminar esta figura?")) return;
    try {
      await remove(id);
      setSuccessMsg("Figura eliminada correctamente.");
      setTimeout(() => navigate("/figuras"), 1200);
    } catch {
      setError("No se pudo eliminar la figura.");
    }
  };

  if (loading) {
    return (
      <div className="d-flex justify-content-center mt-5">
        <div className="spinner-border" role="status" aria-label="Cargando"></div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="alert alert-danger mt-4" role="alert">
        {error}
      </div>
    );
  }

  if (!figura) {
    return null;
  }

  return (
    <div className="container mt-4">
      {successMsg && (
        <div className="alert alert-success" role="alert">
          {successMsg}
        </div>
      )}
      <div className="row g-4 justify-content-center align-items-start">
        {figura.imagen && (
          <div className="col-12 col-md-5">
            <div className="card bg-dark text-light shadow-sm h-100">
              <img
                src={figura.imagen}
                className="card-img-top"
                alt={figura.nombre}
                style={{ objectFit: "cover", height: "350px" }}
              />
            </div>
          </div>
        )}
        <div className={figura.imagen ? "col-12 col-md-7" : "col-12 col-md-8"}>
          <div className="card bg-dark text-light shadow-sm h-100">
            <div className="card-body">
              <h3 className="card-title mb-3">{figura.nombre}</h3>
              <h5 className="card-subtitle mb-2 text-info">{figura.anime}</h5>
              <p className="mb-2">
                <strong>Personaje:</strong> {figura.personaje}
              </p>
              <div className="mb-3">
                <span className="badge bg-info text-dark me-2 fs-6">
                  ${figura.precio}
                </span>
                <span className="badge bg-warning text-dark fs-6">
                  Stock: {figura.stock}
                </span>
                {figura.malId && (
                  <span className="badge bg-secondary ms-2">
                    malId: {figura.malId}
                  </span>
                )}
              </div>
              <div className="d-flex gap-2 mt-4">
                <button
                  className="btn btn-secondary"
                  onClick={() => navigate("/figuras")}
                >
                  <i className="bi bi-arrow-left me-1"></i>
                  Volver
                </button>
                <button
                  className="btn btn-primary"
                  onClick={() => navigate(`/figuras/editar/${figura._id}`)}
                >
                  <i className="bi bi-pencil-square me-1"></i>
                  Editar
                </button>
                <button
                  className="btn btn-danger"
                  onClick={handleDelete}
                >
                  <i className="bi bi-trash me-1"></i>
                  Eliminar
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default FiguraDetail;
